class Config:
  OPENPIBO_PATH="/home/pi/openpibo-ex"
  OPENPIBO_DATA_PATH=OPENPIBO_PATH+"/data"
  MP3_TESTDATA_PATH =OPENPIBO_DATA_PATH+"/tmp/mp3"
  IMAGES_TESTDATA_PATH =OPENPIBO_DATA_PATH+"/tmp/images"
  ICON_TESTDATA_PATH =OPENPIBO_DATA_PATH+"/tmp/icons"
  MODEL_PATH=OPENPIBO_DATA_PATH+"/models"
  KAKAO_ACCOUNT="9f3e3744cebcc57809460495093abf79"
